
VERILOG_SOURCES ?= \
    /home/teguhhofstee/aha/garnet/tests/AO22D0BWP16P90.sv \
    /home/teguhhofstee/aha/garnet/tests/AN2D0BWP16P90.sv \
    /home/teguhhofstee/aha/garnet/genesis_verif/memory_core.sv \
    /home/teguhhofstee/aha/garnet/genesis_verif/mem_unq1.v \
    /home/teguhhofstee/aha/garnet/genesis_verif/sram_stub_unq1.v \
    /home/teguhhofstee/aha/garnet/genesis_verif/doublebuffer_control_unq1.sv \
    /home/teguhhofstee/aha/garnet/genesis_verif/fifo_control_unq1.sv \
    /home/teguhhofstee/aha/garnet/genesis_verif/linebuffer_control_unq1.sv \
    /home/teguhhofstee/aha/garnet/genesis_verif/sram_control_unq1.sv \
    /home/teguhhofstee/aha/garnet/peak_core/DW_fp_mult.v \
    /home/teguhhofstee/aha/garnet/peak_core/DW_fp_add.v \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/cfg_ifc.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/global_buffer_param.svh \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/global_buffer_pkg.svh \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/global_buffer.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_tile.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_tile_int.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_tile_cfg.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_tile_cfg_ctrl.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_tile_pc_switch.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_core_proc_router.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_core_strm_router.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_core_pc_router.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_dummy_start.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_dummy_end.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_core.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_bank.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_core_store_dma.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_core_load_dma.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_core_pc_dma.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_core_switch.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_core_strm_mux.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_core_sram_cfg_ctrl.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_bank_memory.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_bank_ctrl.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_bank_sram_gen.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/glb_shift.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/rtl/TS1N16FFCLLSBLVTC2048X64M8SW.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/systemRDL/output/glb_jrdl_decode.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/systemRDL/output/glb_jrdl_logic.sv \
    /home/teguhhofstee/aha/garnet/global_buffer/systemRDL/output/glb_pio.sv \
    /home/teguhhofstee/aha/garnet/global_controller/design/genesis_verif/glc_axi_addrmap.sv \
    /home/teguhhofstee/aha/garnet/global_controller/design/genesis_verif/jtag.sv \
    /home/teguhhofstee/aha/garnet/global_controller/design/genesis_verif/cfg_and_dbg_unq1.sv \
    /home/teguhhofstee/aha/garnet/global_controller/design/genesis_verif/global_controller.sv \
    /home/teguhhofstee/aha/garnet/global_controller/design/genesis_verif/tap_unq1.sv \
    /home/teguhhofstee/aha/garnet/global_controller/design/genesis_verif/glc_axi_ctrl.sv \
    /home/teguhhofstee/aha/garnet/global_controller/design/genesis_verif/flop_unq3.sv \
    /home/teguhhofstee/aha/garnet/global_controller/design/genesis_verif/glc_jtag_ctrl.sv \
    /home/teguhhofstee/aha/garnet/global_controller/design/genesis_verif/flop_unq2.sv \
    /home/teguhhofstee/aha/garnet/global_controller/design/genesis_verif/flop_unq1.sv \
    /home/teguhhofstee/aha/garnet/global_controller/systemRDL/output/glc_jrdl_decode.sv \
    /home/teguhhofstee/aha/garnet/global_controller/systemRDL/output/glc_pio.sv \
    /home/teguhhofstee/aha/garnet/global_controller/systemRDL/output/glc_jrdl_logic.sv \
    /cad/synopsys/syn/P-2019.03/dw/sim_ver/DW_tap.v \
    /home/teguhhofstee/aha/shale/shale/extras/garnet.sv \
    /home/teguhhofstee/aha/shale/shale/extras/garnet_top.sv

TESTCASE?=test_app
TOPLEVEL?=Garnet_TB
TOPLEVEL_LANG=verilog
MODULE=tb
COCOTB_HDL_TIMEPRECISION=1ps
COCOTB_HDL_TIMESTEP=1ps

ifeq ($(SIM), vcs)
    override COMPILE_ARGS += -LDFLAGS -Wl,--no-as-needed
    override COMPILE_ARGS += -top $(TOPLEVEL)
else ifeq ($(SIM), ius)
    LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6
else ifeq ($(SIM), xcelium)
    SHM_RESET_DEFAULTS=1
endif

include $(shell cocotb-config --makefiles)/Makefile.sim
